apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-pod-identifier
  labels:
    app: scalable-pod-identifier
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: scalable-pod-identifier
  template:
    metadata:
      labels:
        app: scalable-pod-identifier
    spec:
      containers:
        - name: scalable-pod-identifier
          image: ghcr.io/spomprt/scalable-pod-identifier:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "600Mi"
            limits:
              memory: "600Mi"   # CPU-лимит умышленно не ставим, чтобы избежать throttling
          env:
            # Если у вас есть явные настройки, добавьте сюда.
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=60 -XX:+ExitOnOutOfMemoryError"
---
apiVersion: v1
kind: Service
metadata:
  name: scalable-pod-identifier
  labels:
    app: scalable-pod-identifier
spec:
  selector:
    app: scalable-pod-identifier
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
